apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zcp-oidc-postgresql
  name: zcp-oidc-postgresql
  #namespace: zcp-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-block-silver
